[build]
cargo = "/build/mrustc-0.10.1/run_rustc/output/prefix/bin/cargo"
rustc = "/build/mrustc-0.10.1/run_rustc/output/prefix/bin/rustc"
docs = false
vendor = true
extended = true
tools = ["cargo"]

[rust]
channel = "stable"
