[build]
cargo = "/build/rustc-1.44.1/build/x86_64-unknown-linux-gnu/stage2-tools-bin/cargo"
rustc = "/build/rustc-1.44.1/build/x86_64-unknown-linux-gnu/stage2/bin/rustc"
docs = false
vendor = true
extended = true
tools = ["cargo"]

[rust]
channel = "stable"
