change-id = 131075

[build]
cargo = "/build/rustc-1.82.0/build/x86_64-unknown-linux-gnu/stage2-tools-bin/cargo"
rustc = "/build/rustc-1.82.0/build/x86_64-unknown-linux-gnu/stage2/bin/rustc"
docs = false
vendor = true
extended = true
tools = ["cargo"]

[llvm]
download-ci-llvm = false

[rust]
channel = "stable"
