change-id = 116881

[build]
cargo = "/build/mrustc-0.11.0/run_rustc/output-1.74.0/prefix/bin/cargo"
rustc = "/build/mrustc-0.11.0/run_rustc/output-1.74.0/prefix/bin/rustc"
docs = false
vendor = true
extended = true
tools = ["cargo"]

[rust]
channel = "stable"
