change-id = 129295

[build]
cargo = "/build/rustc-1.81.0/build/x86_64-unknown-linux-gnu/stage1-tools-bin/cargo"
rustc = "/build/rustc-1.81.0/build/x86_64-unknown-linux-gnu/stage1/bin/rustc"
docs = false
vendor = true
extended = true
tools = ["cargo"]

[rust]
channel = "stable"
